#Problem 32: Write a function mutate to compute all words generated by a single mutation on a given word. 
#A mutation is defined as inserting a character, deleting a character, replacing a character, 
#or swapping 2 consecutive characters in a string.
#For simplicity consider only letters from a to z.

def mutate(word):
    words_list = []
    
    alphabets = 'abcdefghijklmnopqrstuvwxyz'

    for i in range(len(word)+1):
        for j in range(len(alphabets)):
            a = list(word)
            a.insert(i, alphabets[j])
            words_list.append(''.join(a))
        
    for i in range(len(word)):
        b = word.replace(word[i], '')
        words_list.append(b)
    
    for i in range(len(word)):
        for j in range(len(alphabets)):
            c = word.replace(word[i], alphabets[j])
            words_list.append(c)
            
    for i in range(len(word) - 1):
        j = i + 1
        new = ''
        d = list(word)
        d[i], d[j] = d[j], d[i]
        for char in d:
            new += char
        words_list.append(new)
        
    return words_list




            
            
    
    